#!/bin/bash
# Generates settings.php and trusted-hosts.settings.php from runtime env.
# Settings.php is written once and locked 0440. Trusted hosts are regenerated
# every boot so URL changes flow through without rebuilding the image.

# Emits the s3fs settings.php block. Credentials are read at runtime via
# getenv() so they are not baked as literals into settings.php. The
# takeover flags and $config overrides make Drupal route private files
# through the shared S3 bucket without depending on the admin form. When
# DRX_S3_REQUIRED=0 (CI/build) the block guards on env and stays inert.
drx::settings::_s3_block() {
    cat <<'PHP'
// Shared S3 connection (Litestream + Drupal file storage). The s3fs
// module is enabled at bootstrap when DRX_S3_REQUIRED=1; the values
// below are read only when that module is active.
//
// Security posture: private files are stored under the private prefix
// and served only via Drupal access checks. Public files live under a
// separate prefix that the bucket policy exposes to anonymous GET.
// Upload visibility is decided per field (no global force-private).
if (getenv('DRX_S3_REQUIRED') !== '0') {
  $settings['s3fs.access_key']         = getenv('DRX_S3_ACCESS_KEY_ID') ?: '';
  $settings['s3fs.secret_key']         = getenv('DRX_S3_SECRET_ACCESS_KEY') ?: '';
  // Drupal requires file_private_path to exist before it registers the
  // private:// stream wrapper — even when s3fs is taking it over. The
  // directory only holds a placeholder; s3fs routes actual writes to S3.
  $settings['file_private_path']       = getenv('DRUPAL_PRIVATE_FILES_PATH') ?: '/var/drupal-private';
  // Take over both stream wrappers so every file routes through S3.
  $settings['s3fs.use_s3_for_public']  = TRUE;
  $settings['s3fs.use_s3_for_private'] = TRUE;
  // Respect per-field public/private choice (do not force everything private).
  $settings['s3fs.upload_as_private']  = FALSE;

  // Connection details flow from env into s3fs module config. These
  // overrides survive config import — operator changes in the UI will
  // not stick, so the bucket and credentials remain ops-controlled.
  $config['s3fs.settings']['bucket']                  = getenv('DRX_S3_BUCKET') ?: '';
  $config['s3fs.settings']['region']                  = getenv('DRX_S3_REGION') ?: 'us-east-1';
  $config['s3fs.settings']['public_folder']           = getenv('DRX_S3_PREFIX_PUBLIC')  ?: 'public';
  $config['s3fs.settings']['private_folder']          = getenv('DRX_S3_PREFIX_PRIVATE') ?: 'private';
  $config['s3fs.settings']['root_folder']             = '';
  $config['s3fs.settings']['use_customhost']          = getenv('DRX_S3_ENDPOINT') ? TRUE : FALSE;
  $config['s3fs.settings']['hostname']                = getenv('DRX_S3_ENDPOINT') ?: '';
  $config['s3fs.settings']['use_path_style_endpoint'] = getenv('DRX_S3_ENDPOINT') ? TRUE : FALSE;
  $config['s3fs.settings']['use_https']               = (strpos(getenv('DRX_S3_ENDPOINT') ?: 'https://', 'https://') === 0) ? TRUE : FALSE;
  $config['s3fs.settings']['encryption']              = '';
}
PHP
}

drx::settings::_db_block() {
    case "${DRUPAL_DB_DRIVER}" in
        sqlite)
            cat <<PHP
\$databases['default']['default'] = [
  'driver'   => 'sqlite',
  'database' => '${DRUPAL_SQLITE_PATH}',
  'prefix'   => '',
];
PHP
            ;;
        mysql|pgsql)
            cat <<PHP
\$databases['default']['default'] = [
  'driver'   => '${DRUPAL_DB_DRIVER}',
  'host'     => getenv('DRUPAL_DB_HOST') ?: 'localhost',
  'port'     => getenv('DRUPAL_DB_PORT') ?: '',
  'database' => getenv('DRUPAL_DB_NAME') ?: '',
  'username' => getenv('DRUPAL_DB_USER') ?: '',
  'password' => getenv('DRUPAL_DB_PASS') ?: '',
  'prefix'   => '',
];
PHP
            ;;
        *)
            drx::die "Unsupported DRUPAL_DB_DRIVER: ${DRUPAL_DB_DRIVER}"
            ;;
    esac
}

drx::settings::write() {
    if [ ! -f "${DRUPAL_SETTINGS_PHP}" ]; then
        drx::log "Generating settings.php"
        chmod u+w "${DRUPAL_SITE_DIR}" 2>/dev/null || true

        local hash_salt
        hash_salt="$(head -c 55 /dev/urandom | base64 | tr -d '+/=' | head -c 55)"

        local db_block
        db_block="$(drx::settings::_db_block)"

        local s3_block
        s3_block="$(drx::settings::_s3_block)"

        cat > "${DRUPAL_SETTINGS_PHP}" <<PHP
<?php
// Generated by drx-apiserver base image. Do not edit by hand; override via hooks.

${db_block}

${s3_block}

\$settings['config_sync_directory']    = '${DRUPAL_CONFIG_SYNC_DIR}';
\$settings['hash_salt']                = '${hash_salt}';
\$settings['update_free_access']       = FALSE;
\$settings['container_yamls'][]        = DRUPAL_ROOT . '/sites/default/services.yml';
\$settings['file_scan_ignore_directories'] = ['node_modules', 'bower_components'];
\$settings['entity_update_batch_size'] = 50;

if (file_exists(DRUPAL_ROOT . '/sites/default/trusted-hosts.settings.php')) {
  include DRUPAL_ROOT . '/sites/default/trusted-hosts.settings.php';
}

if (file_exists(DRUPAL_ROOT . '/sites/default/settings.local.php')) {
  include DRUPAL_ROOT . '/sites/default/settings.local.php';
}
PHP
        chown www-data:www-data "${DRUPAL_SETTINGS_PHP}"
        chmod 0440 "${DRUPAL_SETTINGS_PHP}"
    fi

    drx::settings::_write_trusted_hosts
}

drx::settings::_write_trusted_hosts() {
    local backend_host backend_re extras="" pat
    backend_host="$(drx::normalize_hostname "${DRUPAL_HOSTNAME:-${BACKEND_URL}}")"
    backend_re="$(drx::escape_regex "${backend_host}")"

    if [ -n "${DRUPAL_TRUSTED_HOST_PATTERNS}" ]; then
        IFS=',' read -ra _patterns <<< "${DRUPAL_TRUSTED_HOST_PATTERNS}"
        for pat in "${_patterns[@]}"; do
            pat="$(echo "${pat}" | xargs)"
            [ -n "${pat}" ] && extras+="  '${pat}',"$'\n'
        done
    fi

    drx::log "Writing trusted-hosts.settings.php (backend=${backend_host})"
    cat > "${DRUPAL_TRUSTED_HOSTS_PHP}" <<PHP
<?php
\$settings['trusted_host_patterns'] = [
  '^localhost(:\\d+)?\$',
  '^127\\.0\\.0\\.1(:\\d+)?\$',
  '^${backend_re}(:\\d+)?\$',
${extras}];
PHP
    chown www-data:www-data "${DRUPAL_TRUSTED_HOSTS_PHP}"
    chmod 0440 "${DRUPAL_TRUSTED_HOSTS_PHP}"
}
