#!/bin/bash
# Generates settings.php and trusted-hosts.settings.php from runtime env.
# Settings.php is written once and locked 0440. Trusted hosts are regenerated
# every boot so URL changes flow through without rebuilding the image.

drx::settings::_db_block() {
    case "${DRUPAL_DB_DRIVER}" in
        sqlite)
            cat <<PHP
\$databases['default']['default'] = [
  'driver'   => 'sqlite',
  'database' => '${DRUPAL_SQLITE_PATH}',
  'prefix'   => '',
];
PHP
            ;;
        mysql|pgsql)
            cat <<PHP
\$databases['default']['default'] = [
  'driver'   => '${DRUPAL_DB_DRIVER}',
  'host'     => getenv('DRUPAL_DB_HOST') ?: 'localhost',
  'port'     => getenv('DRUPAL_DB_PORT') ?: '',
  'database' => getenv('DRUPAL_DB_NAME') ?: '',
  'username' => getenv('DRUPAL_DB_USER') ?: '',
  'password' => getenv('DRUPAL_DB_PASS') ?: '',
  'prefix'   => '',
];
PHP
            ;;
        *)
            drx::die "Unsupported DRUPAL_DB_DRIVER: ${DRUPAL_DB_DRIVER}"
            ;;
    esac
}

drx::settings::write() {
    if [ ! -f "${DRUPAL_SETTINGS_PHP}" ]; then
        drx::log "Generating settings.php"
        chmod u+w "${DRUPAL_SITE_DIR}" 2>/dev/null || true

        local hash_salt
        hash_salt="$(head -c 55 /dev/urandom | base64 | tr -d '+/=' | head -c 55)"

        local db_block
        db_block="$(drx::settings::_db_block)"

        cat > "${DRUPAL_SETTINGS_PHP}" <<PHP
<?php
// Generated by drx-drupal-base. Do not edit by hand; override via hooks.

${db_block}

\$settings['config_sync_directory']    = '${DRUPAL_CONFIG_SYNC_DIR}';
\$settings['hash_salt']                = '${hash_salt}';
\$settings['update_free_access']       = FALSE;
\$settings['container_yamls'][]        = DRUPAL_ROOT . '/sites/default/services.yml';
\$settings['file_scan_ignore_directories'] = ['node_modules', 'bower_components'];
\$settings['entity_update_batch_size'] = 50;

if (file_exists(DRUPAL_ROOT . '/sites/default/trusted-hosts.settings.php')) {
  include DRUPAL_ROOT . '/sites/default/trusted-hosts.settings.php';
}

if (file_exists(DRUPAL_ROOT . '/sites/default/settings.local.php')) {
  include DRUPAL_ROOT . '/sites/default/settings.local.php';
}
PHP
        chown www-data:www-data "${DRUPAL_SETTINGS_PHP}"
        chmod 0440 "${DRUPAL_SETTINGS_PHP}"
    fi

    drx::settings::_write_trusted_hosts
}

drx::settings::_write_trusted_hosts() {
    local backend_host backend_re extras="" pat
    backend_host="$(drx::normalize_hostname "${DRUPAL_HOSTNAME:-${BACKEND_URL}}")"
    backend_re="$(drx::escape_regex "${backend_host}")"

    if [ -n "${DRUPAL_TRUSTED_HOST_PATTERNS}" ]; then
        IFS=',' read -ra _patterns <<< "${DRUPAL_TRUSTED_HOST_PATTERNS}"
        for pat in "${_patterns[@]}"; do
            pat="$(echo "${pat}" | xargs)"
            [ -n "${pat}" ] && extras+="  '${pat}',"$'\n'
        done
    fi

    drx::log "Writing trusted-hosts.settings.php (backend=${backend_host})"
    cat > "${DRUPAL_TRUSTED_HOSTS_PHP}" <<PHP
<?php
\$settings['trusted_host_patterns'] = [
  '^localhost(:\\d+)?\$',
  '^127\\.0\\.0\\.1(:\\d+)?\$',
  '^${backend_re}(:\\d+)?\$',
${extras}];
PHP
    chown www-data:www-data "${DRUPAL_TRUSTED_HOSTS_PHP}"
    chmod 0440 "${DRUPAL_TRUSTED_HOSTS_PHP}"
}
